### ISSUE TITLE
The proguard rule does not work on MI4 (Android 4.4)

### ISSUE THREAD

**Issue by breezehou** [frankiesardo/icepick#123]
If use the following rule, it will be crashed on Android 4.4:
`
-dontwarn icepick.**
-keep class icepick.** { *; }
-keep class **$$Icepick { *; }
-keepclasseswithmembernames class * {
    @icepick.* <fields>;
}
-keepnames class * { @icepick.State *;}
`
Crash logs (I used apache commons lib in my project):
`
java.lang.NoSuchMethodError: org.apache.commons.lang3.StringUtils.a
... ...
`
If I removed <-keepnames class * { @icepick.State *;}> line, it works, I don't know why.
